export const ADD_HISTORY = "ADD_HISTORY";

export const DISPLAY_LOADING ='DISPLAY_LOADING';

export const HIDE_LOADING ='HIDE_LOADING';

export const OPEN_DRAWER ='OPEN_DRAWER';

export const OPEN_FORM_CREATE_TASK='OPEN_FORM_CREATE_TASK';

export const SET_SUBMIT_CREATE_TASK ='SET_SUBMIT_CREATE_TASK';

export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const GET_ALL_STATUS_SAGA ='GET_ALL_STATUS_SAGA';

export const GET_ALL_STATUS= 'GET_ALL_STATUS';

export const GET_ALL_PRIORITY ='GET_ALL_PRIORITY';

export const HANDLE_CHANGE_POST_API = 'HANDLE_CHANGE_POST_API';