/**==================Saga ==================== */
 export const GET_LIST_PROJECT_SAGA ='GET_LIST_PROJECT_SAGA';

 export const DELETE_USER_PROJECT_SAGA='DELETE_USER_PROJECT_SAGA';

 export const DELETE_PROJECT_SAGA='DELETE_PROJECT_SAGA';

 export const GET_PORJECT_CATEGORY_SAGA ='GET_PORJECT_CATEGORY_SAGA';

 export const SET_SUBMIT_EDIT_PROJECT='SET_SUBMIT_EDIT_PROJECT';

 /**========================Reducer================ */

 export const OPEN_FROM_EDIT_PROJECT= 'OPEN_FROM_EDIT_PROJECT';

 export const EDIT_PROJECT='EDIT_PROJECT';

 export const GET_lIST_PROJECT='GET_lIST_PROJECT';


 export const PROJECT_DETAIL= 'PROJECT_DETAIL';

 export const GET_ALL_PROJECT_CATEGORY= 'GET_ALL_PROJECT_CATEGORY';

 export const UPDATE_PROJECT_SAGA ='UPDATE_PROJECT_SAGA';

 export const CREATE_PROJECT_SAGA ='CREATE_PROJECT_SAGA';

 export const GET_PROJECT_DETAIL_SAGA ='GET_PROJECT_DETAIL_SAGA';
