export const  GET_TASK_DETAIL ='GET_TASK_DETAIL';

export const CHANGE_TASK_MODAL = 'CHANGE_TASK_MODAL';


export const CHANGE_ASSIGNESS ='CHANGE_ASSIGNESS';

export const REMOVE_USER_ASSIGNESS ='REMOVE_USER_ASSIGNESS';